Set DeviceName to Environment.MachineName
stackify/stackify-api-dotnet pull request #107
Opened 2021-01-27 14:04 UTC by marcdemz

2021-02-02 17:39 UTC, kbond-stackify requested changes
The API still needs the special code logic for EC2 instance names, but not the AzureInstanceName logic.

2021-02-04 11:16 UTC, marcdemz commented
> The API still needs the special code logic for EC2 instance names, but not the AzureInstanceName logic.

added back logic for EC2 instance names

2021-02-04 15:30 UTC, kbond-stackify approved these changes

2021-02-11 22:01 UTC, homiedopie approved these changes

2021-02-11 22:01 UTC, merged